#!/bin/bash

cat <<- 'EOF'
 _                             
| |__   __ _ _ __   ___  _ __  
| '_ \ / _` | '_ \ / _ \| '_ \ 
| |_) | (_| | | | | (_) | | | |
|_.__/ \__,_|_| |_|\___/|_| |_|

Anonymous bash - the incognito mode for your shell

EOF

read -r -d '' BASHRC << 'EOF'

export HISTFILE=/dev/null
PS1='[anon@host \W]\$ '

EOF

bash --rcfile <(echo "$BASHRC")

