#!/bin/bash

# batch - bat + watch
# yea its a weird name
# its basically a file content monitor
# similar to what vscode and others do out of the box

if [ ! -x "$(command -v bat)" ]
then
	echo "Error: please install bat into your PATH"
	exit 1
fi
if ! bat -h | grep -q "cat.*clone with wings"
then
	echo "Error: did not find a suitable bat tool"
	exit 1
fi
if [ ! -x "$(command -v inotifywait)" ]
then
	distro="$(cat /etc/os-release | grep '^NAME="' | cut -d'"' -f2 | awk '{ print $1 }')"
	echo "Error: please install inotifywait"
	echo ""
	if [ "$distro" == "Debian" ]
	then
		echo "       sudo apt-get install -y inotify-tools"
	else
		echo "       sudo pacman -Sy inotify-tools"
	fi
	echo ""
	exit 1
fi

function listen() {
	clear
	bat --paging=never "$@"
	while true
	do
		while read -r
		do
			clear
			bat --paging=never "$@"
		done < <(inotifywait -q -e modify -r .)
		# done < <(inotifywait -q -e modify "$filename")
	done
}

if [ "$#" -eq "0" ]
then
	echo "usage: batch [FILE..]"
	echo "description: watch file contents"
	echo "example: batch *.c"
	exit 1
fi

for f in "$@"
do
	if [[ ! -f "$f" ]]
	then
		echo "Error: file not found $f"
		exit 1
	fi
	if [[ "${f::1}" == "/" ]]
	then
		echo "Error: file can not be absolute '$f'"
		exit 1
	fi
	if [[ "${f::2}" == ".." ]]
	then
		echo "Error: file can not be above current dir '$f'"
		exit 1
	fi
done

listen "$@"

