#!/bin/bash
# buffer pstd - creates paste from buffer and updates buffer to url
# dependencys:
# install cstd and xsel
# https://github.com/ChillerDragon/cstd
# sudo apt install xsel
# wrapper to create paste of stdin
# i might leak stuff accidentally to a paste service that does never delet stuff loooool

function os_copy() {
if [ "$(uname)" == "Darwin" ]
then
    echo "$1" | pbcopy
else
    echo "$1" | xsel -ib
fi
}

function os_paste() {
if [ "$(uname)" == "Darwin" ]
then
    pbpaste
else
    xsel -b
fi
}

buffer=$(os_paste)
echo "$buffer"
if [[ "$1" != "-yes" ]]
then
    echo "do you want this to be published online for ever? [y/N]"
    read -r -n 1 yn
    echo ""
    if [[ ! "$yn" =~ [yY] ]]
    then
        echo "abort buffer paste."
        exit
    fi
fi

mkdir -p /tmp/crools-"$USER"/bstd/
tmp_file="$(mktemp /tmp/crools-"$USER"/bstd/clipboard_XXXXXXXXXXXXX.txt)"

echo "$buffer" > "$tmp_file"
paste=$(cstd "$tmp_file")
echo "$paste"
os_copy "$paste"

