#!/bin/bash

function git_save_pull() {
    local repo
    repo=${1:-crools}
    if [ "$(git status | tail -n1)" != "nothing to commit, working tree clean" ]
    then
        echo "WARNING: git pull failed! Is your $repo working tree clean?"
        return
    fi
	echo "[*] updating $repo ..."
    git pull
}

crools_dir="${0%/*}"
if [ ! -d "$crools_dir" ]
then
    echo "Error: invalid crools dir"
    echo "$crools_dir"
    exit 1
fi

cd "$crools_dir" || exit 1

if [ "$1" == "--dev" ]
then
    exec "$SHELL"
else
    git_save_pull
fi

if [ -d ../dotfiles ] && [ -f ../dotfiles/setup.sh ]
then
    cd ../dotfiles || exit 1
    if git remote -v | grep -q '^origin.*ChillerDragon/dotfiles '
    then
        git_save_pull dotfiles
        ./setup.sh
    fi
fi

