#!/bin/bash

echo "[------------------------------------------------------------------]"
echo "[---] ddnet run tests helper (gtest && gui debug integration)  [---]"
echo "[------------------------------------------------------------------]"
echo ""

function check_dir() {
	local dir="$1"
	if [ ! -d "$dir" ]
	then
		echo "Error: $dir dir not found!"
		echo "       make sure you are at the root of a ddnet repo"
		exit 1
	fi
}

function check_bin() {
	local bin="$1"
	if [ ! -x "$(command -v "$bin")" ]
	then
		echo "Error: you need $bin installed in your PATH"
		exit 1
	fi
}

check_dir .git
check_dir cmake
check_dir src

check_bin clang
check_bin ninja
check_bin cmake
check_bin valgrind

if [ ! -f CMakeLists.txt ]
then
	echo "Error: CMakeLists.txt not found!"
	echo "       make sure your are at the root of a ddnet repo"
	exit 1
fi

mkdir -p build-integration-tests-gui
cd build-integration-tests-gui || exit 1

if [ ! -f Makefile ]
then
	cmake -G Ninja \
		-DDOWNLOAD_GTEST=OFF \
		-DHEADLESS_CLIENT=OFF \
		-DCMAKE_BUILD_TYPE=Debug \
		-Werror=dev ..
fi

cmake --build . --config Debug || exit 1

# needed for integration tests
test -f chillerbot-ux && cp chillerbot-ux DDNet
# test -f term-ux && cp term-ux DDNet

./integration_test.sh --valgrind-memcheck || exit 1

