#!/bin/bash

echo "ddnet code base linter"
echo "runs similiar stuff like the CI"

ctidy || exit 1
./scripts/fix_style.py --dry-run || exit 1
./scripts/check_header_guards.py || exit 1
find . -type f -name '*.sh' -print0 | xargs -0 shellcheck || exit 1
if grep -Eqr '(msg|Print).*\(.*"[Ee]rror:' src/;
then
	echo "Expected log errors to be in this format 'ERROR: error message'"
	echo "Found these non uppercased log errors:"
	grep -Er '(msg|Print).*\(.*"[Ee]rror:' src/
	exit 1
fi
find . -type f -name "*.py" -not -path './ddnet-libs/*' -not -path './googletest-src/*' -print0 | xargs -0 pylint || exit 1
find src -name '*.h' | while read -r i; do grep -r -q "$(basename "$i")" || (echo "Header file $i is unused" && exit 1); done

