#!/bin/bash
#
# fuzzy wireshark wrapper
# i should probably build a more generic
#
# f (app)
#
# alias.. but yea.
# watever

fdbin=fd

if ! fd -h 2>&1 | grep -q "A program to find entries in your filesystem" &> /dev/null
then
	if fdfind -h | grep -q "A program to find entries in your filesystem"
	then
		fdbin=fdfind
	else
		echo "Error: please install 'fd' the rust 'find' alternative"
		source /etc/os-release
		if [ "$ID" == "debian" ]
		then
			echo ""
			echo "   sudo apt install fd-find"
			echo ""
		fi
		exit 1
	fi
fi

if [ ! -x "$(command -v fzf)" ]
then
	echo "Error: missing fzf"
	exit 1
fi

if [ ! -x "$(command -v wireshark)" ]
then
	echo "Error: missing wireshark"
	exit 1
fi

pcap="$($fdbin -tf -e pcap -e pcapng -e dump | fzf)"

if [ "$pcap" == "" ]
then
	echo "Aborting ..."
	exit 1
fi

if [ ! -f "$pcap" ]
then
	echo "Error: file not found '$pcap'"
	exit 1
fi

echo '(((!(tw7.msg == "sys.input")) && !(tw7.msg == "sys.snap_single")) && !(tw7.msg == "sys.input_timing")) && !(tw7.msg == "sys.snap_empty")'
wireshark "$pcap"

