#!/bin/bash
# shellcheck disable=SC1117

cat << EOF
                      _
  ___ _ __ ___   ___ | |___
 / __| '__/ _ \ / _ \| / __|
| (__| | | (_) | (_) | \__ \\
 \___|_|  \___/ \___/|_|___/

OPENSHOT-QT LAUNCH FROM SOURCE SCRIPT

EOF

OPENSHOT=/home/$USER/Desktop/git-extern/openshot-qt
LIBOPENSHOT=/home/$USER/Desktop/git-extern/libopenshot

if [ ! -d "$OPENSHOT" ]
then
	echo "Error: openshot-qt is not installed at expected location"
	echo "$OPENSHOT"
	exit 1
fi

if [ ! -d "$LIBOPENSHOT" ]
then
	echo "Error: libopenshot is not installed at expected location"
	echo "$LIBOPENSHOT"
	exit 1
fi

cd "$OPENSHOT" || exit 1
export PYTHONPATH=$LIBOPENSHOT/build/src/bindings/python
python3 src/launch.py

