#!/bin/bash
# crapshot - take screenshot and scp it to your fav zzh remote
#
# if super motivated create a recording tool out of this and create quick video snippets
# ffmpeg -video_size $(xrandr | fgrep '*' | xargs | cut -d' ' -f1) -framerate 60 -f x11grab -i $DISPLAY -c:v libx264 -qp 0 -preset ultrafast ffmpeg.mp4
#
# make sure the first zzh host has permissions and opentube running
conf_dir=~/.config/crools
conf=~/.config/crools/zzh.cnf
env_file=~/.config/crools/opentube.env
OPENTUBE_ROOT=/var/www/OpenTube

function os_copy() {
if [ "$(uname)" == "Darwin" ]
then
    echo "$1" | pbcopy
else
    echo "$1" | xsel -ib
fi
}
function edit_cnf() {
    if [ ! -f $conf ]
    then
        echo "Error: could not edit config (not found)."
        exit 1
    fi
    crools_find_editor $conf || { echo "Error: failed to edit config"; exit 1; }
}
function check_conf() {
    if [ ! -f $conf ]
    then
        echo "config file not found!"
        echo "Do you want to create one? [y/N]"
        read -r -n 1 yn
        echo ""
        if [[ ! "$yn" =~ [yY] ]]
        then
            return
        fi
        mkdir -p "$conf_dir"
        {
            echo "# zzh - config"
            echo "# store your fav ssh commands here"
            echo "ssh crools@localhost"
            echo "ssh chillerdragon@149.202.127.134"
        } > "$conf"
        edit_cnf
    fi
}
function edit_env() {
    if [ ! -f $conf ]
    then
        echo "Error: could not edit env file (not found)."
        exit 1
    fi
    crools_find_editor "$env_file"|| { echo "Error: failed to env file"; exit 1; }
}
function check_env {
	if [ -f "$env_file" ]
	then
		return
	fi
        echo "env file not found!"
        echo "Do you want to create one? [y/N]"
        read -r -n 1 yn
        echo ""
        if [[ ! "$yn" =~ [yY] ]]
        then
            return
        fi
        mkdir -p "$conf_dir"
        {
            echo "# opentube token"
	    echo "# generate one at https://zillyhuhn.com/OpenTube/php/profile.php"
            echo "OPENTUBE_TOKEN=mytoken"
        } > "$env_file"
        edit_env

}
if [ "$1" == "--help" ] || [ "$1" == "-h" ]
then
    echo "usage: $(basename "$0") <video> [OPTION]"
    echo "options:"
    echo "  --unlisted              upload unlisted video"
    echo "  --user|-u <username>    upload to user dir"
    echo "description: upload videos to opentube"
    exit 0
fi

check_conf
check_env
if [ ! -f "$conf" ]
then
	echo "Error: config missing"
	exit 1
fi
if [ ! -f "$env_file" ]
then
	echo "Error: env file missing"
	exit 1
fi

source "$env_file"

while IFS= read -r line
do
    if [ "${line:0:1}" == "#" ]
    then
        continue
    fi
    remote="$(echo "$line" | cut -d' ' -f2)"
    host="$(echo "$remote" | cut -d'@' -f2)"
    break
done < $conf

inputfile="$1"
inputfile_base="$(basename "$inputfile")"
viddir="$OPENTUBE_ROOT/videos/saved"
url="https://tube.$host/video.php?t=$inputfile_base"
user=''
if [ "$2" == "--unlisted" ]
then
    viddir="$OPENTUBE_ROOT/videos/unlisted"
    url="https://tube.$host/video.php?t=$inputfile_base&unlisted=true"
fi
if [ "$2" == "--user" ] || [ "$2" == "-u" ]
then
	user="$3"
	viddir="$OPENTUBE_ROOT/videos/users/$user"
	url="https://tube.$host/video.php?t=$inputfile_base&u=$user"
fi
if ! [[ "$inputfile" =~ ^[0-9A-Za-z\./_-]+$ ]]
then
    echo "Error video title has to be alpha numeric"
    exit 1
fi
if [ ! -f "$inputfile" ]
then
    echo "Error file '$inputfile' not found."
    exit 1
fi
if ! file "$inputfile" | grep -Eq ': (ISO Media|WebM)'
then
    echo "Error filetype has to be ISO Media or WebM"
    exit 1
fi
found="$(curl -o /dev/null -s -w "%{http_code}\\n" "$url")"
if [ "$found" != "404" ]
then
    echo "Error video with this title already exists."
    exit 1
fi
cmd="scp $inputfile $remote:$viddir/$inputfile_base"
echo "$cmd"
eval "$cmd"
echo "$url"
os_copy "$url"


curl 'https://tube.zillyhuhn.com/php/add_video.php' \
	-X POST \
	-H 'Content-Type: application/x-www-form-urlencoded' \
	--data-raw "title=todo&description=todo&filepath=$inputfile&token=$OPENTUBE_TOKEN&username=$user"

