#!/bin/bash
# tool that does my homework for university

pgdp_path=~/Desktop/uni/pgdp
version="0.0.1"

figlet "TUM homework"
cd "$pgdp_path" || exit 1
ex="invalid_exercises"

function err()
{
    echo "[-] $1"
}

if [ "$1" == "--help" ]
then
    echo "usage: $0 [clone url]"
    echo "  tum homework quickstart tool ( v$version )"
    echo "  it will open the latest homework and launch eclipse"
    exit 0
fi
if [ "$#" -gt 0 ]
then
    git clone "$1"
    ex="${1##*/}" # get only repo name from url
    ex="${ex%.*}" # chop of .git
    echo "navigating to exercises '$ex'"
else
    ex=$(grep "h" ./pgdp*/ | sort | tail -n1)
    if [ ! -d "$ex" ]
    then
        err "invalid path '$ex'"
        exit 1
    fi
    echo "latest homework is '$ex'"
fi

cd "$ex" || exit 1
echo " -- global git ---"
git config --global user.name
git config --global user.email
echo " -- current git ---"
git config user.name
git config user.email
echo ""
echo ""
echo ""
# print homework path and copy to clipboard
echo "cd $pgdp_path/$ex"
echo "cd $pgdp_path/$ex" | xsel -ib
echo ""
echo ""
echo ""
firefox "https://artemis.ase.in.tum.de/#/overview/37/exercises" &
if pgrep -x "eclipse" > /dev/null
then
    echo "eclipse running already..."
else
    echo "starting eclipse..."
    # eclipse . & >> "$eclipse_logfile" 2>&1
    eclipse .
fi
# bash

