#!/bin/bash
# tool that does my homework for university

pgdp_path=~/Desktop/uni/pgdp
eclipse_logfile=/tmp/uni_eclipse.log
version="0.0.1"
cd "$pgdp_path"

function err()
{
    echo "[-] $1"
}

figlet "TUM homework"
if [ "$1" == "--help" ]
then
    echo "usage: $0 [clone url]"
    echo "  tum homework quickstart tool ( v$version )"
    echo "  it will open the latest homework and launch eclipse"
    exit 0
fi
if [ "$#" -gt 0 ]
then
    git clone "$1"
fi

hw=$(ls -d pgdp* | grep "h" | sort | tail -n1)
if [ ! -d "$hw" ]
then
    err "invalid path '$hw'"
    exit 1
fi
echo "latest homework is '$hw'"
cd "$hw"
echo ""
echo ""
echo ""
# print homework path and copy to clipboard
echo "cd $pgdp_path/$hw"
echo "cd $pgdp_path/$hw" | xsel -ib
echo ""
echo ""
echo ""
if pgrep -x "eclipse" > /dev/null
then
    echo "eclipse running already..."
else
    echo "starting eclipse..."
    # eclipse . & >> "$eclipse_logfile" 2>&1
    eclipse .
fi
# bash

