#!/bin/bash

logfile="twlog.log"

# censor ips
sed '/^\[.*\]\[server\].*<{.*}>/ { s/<{[0-9].*:/<{XXX.XXX.XXX.XXX:/g }' "$logfile" | \
    sed "/^\\[.*\\]\\[server\\]: '.*' -> '.*'$/ { s/'.*' -> '.*'/'nameless' -> 'nameless'/g }" | \
    cat
    # sed "/^\\[.*\\]\\[chat\\]: .*:.*:.*$/ { s/:.*:(.)*/XXX/g }"
