#!/bin/bash
# zzh - quick select of your fav ssh connections
conf_dir=~/.config/crools
conf=~/.config/crools/zzh.cnf
ismosh=0
ishost=0
pattern=""
arg=""
function edit_cnf() {
    if [ ! -f $conf ]
    then
        echo "Error: could not edit config (not found)."
        exit 1
    fi
    crools_find_editor $conf || { echo "Error: failed to edit config"; exit 1; }
}
function check_conf() {
    if [ ! -f $conf ]
    then
        echo "config file not found!"
        echo "Do you want to create one? [y/N]"
        read -r -n 1 yn
        echo ""
        if [[ ! "$yn" =~ [yY] ]]
        then
            return
        fi
        mkdir -p $conf_dir
        {
            echo "# zzh - config"
            echo "# store your fav ssh commands here"
            echo "ssh crools@localhost"
            echo "ssh chillerdragon@149.202.127.134"
        } >> $conf
        edit_cnf
    fi
}
if [ "$1" == "--help" ] || [ "$1" == "-h" ]
then
    echo "usage: $(tput bold)$(basename "$0") [OPTION]$(tput sgr0)"
    echo "description:"
    echo "  quick select ssh connections"
    echo "options:"
    echo "  $(tput bold)--edit$(tput sgr0)          edit config"
    echo "  $(tput bold)--host <number>$(tput sgr0) get hostname by number"
    echo "  $(tput bold)--help$(tput sgr0)          show this help"
    echo "  $(tput bold)<number>$(tput sgr0)        skip menu and go to number"
    echo "  $(tput bold)/<pattern>$(tput sgr0)      chose first entry matching <pattern>"
    exit 0
elif [ "$1" == "--host" ]
then
    ishost=1
    shift
    if ! [[ "$1" =~ ^[1-9][0-9]*$ ]]
    then
        echo "usage: $(basename "$0") --host <number>"
        exit 1
    fi
elif [ "$1" == "--edit" ] || [ "$1" == "-e" ]
then
    edit_cnf
    exit 0
elif [ "${1:0:1}" == "/" ]
then
    pattern="${1:1}"
elif [ "$1" == "--mosh" ]
then
    ismosh=1
    shift
fi
if [[ "$1" =~ ^[1-9][0-9]*$ ]]
then
    arg="$1"
    arg="$((arg-1))"
fi

check_conf
if [ ! -f $conf ]
then
    echo "Error: config missing"
    exit 1
fi

function cat_conf() {
    if [ "$ismosh" == "1" ]
    then
        sed 's/^ssh /mosh /' "$conf"
    else
        cat "$conf"
    fi
}

options=()
lines=0
while IFS= read -r line
do
    if [ "${line:0:1}" == "#" ]
    then
        continue
    fi
    options+=("$line")
    lines=$((lines+1))
done < <(cat_conf)

# only one entry
if [ $lines -eq 1 ]
then
    eval "${options[0]}"
    exit 0
fi

# match entry
if [ "$pattern" != "" ]
then
    for entry in "${options[@]}"
    do
        if [[ "${entry,,}" =~ ${pattern,,} ]]
        then
            echo "[zzh] matched '$entry'"
            eval "$entry"
            exit 0
        fi
    done
    echo "pattern not found"
    exit 1
fi

# arg entry
if [ "$arg" != "" ]
then
    if [ "${#options[@]}" -lt "$arg" ]
    then
        echo "Error: selected item $arg out of ${#options[@]}"
        exit 1
    fi
    if [ "$ishost" == "1" ]
    then
        echo "${options[$arg]}" | cut -d' ' -f2
    else
        eval "${options[$arg]}"
    fi
    exit 0
fi

# select entry
PS3='Select ssh connection: '
select opt in "${options[@]}"
do
    if [[ " ${options[@]} " =~ " ${opt} " ]]
    then
        eval "$opt"
        exit 0
    else
        echo "invalid option $REPLY"
    fi
done

